package com.zetcode;

public interface Commons {

	int BOARD_WIDTH = 516;
	int BOARD_HEIGHT = 629;
	int TILE_SIZE = 18;
	int WIDTH = 28;
	int HEIGHT = 31;

	int SPEED = 3;

	int GO_DOWN = 15;
	int DELAY = 17;

	static final String[] MAP = { "XXXXXXXXXXXXXXXXXXXXXXXXXXXX", "X............XX............X",
			"X.XXXX.XXXXX.XX.XXXXX.XXXX.X", "XBXOOX.XOOOX.XX.XOOOX.XOOXBX", "X.XXXX.XXXXX.XX.XXXXX.XXXX.X",
			"X..........................X", "X.XXXX.XX.XXXXXXXX.XX.XXXX.X", "X.XXXX.XX.XXXXXXXX.XX.XXXX.X",
			"X......XX....XX....XX......X", "XXXXXX.XXXXXOXXOXXXXX.XXXXXX", "OOOOOX.XXXXXOXXOXXXXX.XOOOOO",
			"OOOOOX.XXOOOOrOOOOOXX.XOOOOO", "OOOOOX.XXOXXXddXXXOXX.XOOOOO", "XXXXXX.OOOXOOOOOOXOOO.XXXXXX",
			"OOOOOO.OOOXbOpOoOXOOO.OOOOOO", "XXXXXX.OOOXOOOOOOXOOO.XXXXXX", "OOOOOX.XXOXXXXXXXXOXX.XOOOOO",
			"OOOOOX.XXOOOOOOOOOOXX.XOOOOO", "OOOOOX.XXOXXXXXXXXOXX.XOOOOO", "XXXXXX.XXOXXXXXXXXOXX.XXXXXX",
			"X............XX............X", "X.XXXX.XXXXX.XX.XXXXX.XXXX.X", "X.XXXX.XXXXX.XX.XXXXX.XXXX.X",
			"XB..XX.......PO.......XX..BX", "XXX.XX.XX.XXXXXXXX.XX.XX.XXX", "XXX.XX.XX.XXXXXXXX.XX.XX.XXX",
			"X......XX....XX....XX......X", "X.XXXXXXXXXX.XX.XXXXXXXXXX.X", "X.XXXXXXXXXX.XX.XXXXXXXXXX.X",
			"X..........................X", "XXXXXXXXXXXXXXXXXXXXXXXXXXXX" };

	boolean[][] walls = new boolean[28][31];
}